<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>FloorPatternFlattener</AssemblyName>
    <RootNamespace>FloorPatternFlattener</RootNamespace>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>$(DefineConstants);REVIT_2023</DefineConstants>
    <RevitVersion>2023</RevitVersion>
    <UseWPF>true</UseWPF>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>$(Revit2023Path)\RevitAPI.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>$(Revit2023Path)\RevitAPIUI.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xaml" />
  </ItemGroup>

    <ItemGroup>
      <Compile Include="..\FloorPatternFlattener.Core\**\*.cs" Link="Shared\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
  <ItemGroup>
    <Compile Include="RevitYearInfo.cs" />
  </ItemGroup>
</Project>
